### ISSUE TITLE
/authors endpoint

### ISSUE THREAD

**Issue by jackleslie** [WizardOfMenlo/LatinDiachronicDatabase#1]
It would be useful to have an endpoint to retrieve the authors in the database for

- Author autocomplete for the intersection search
- Results filtering / advanced search for lemmata

**Comment by WizardOfMenlo** [comment]
Should be a relatively easy feature to implement, I will be adding two endpoints, ```/authors/``` for fetching all authors, and ```/authorsHist/{date}``` to fetch all authors before a certain date. Both endpoints should always return an array of authors' names

**Comment by WizardOfMenlo** [comment]
Implemented with commit #298c8, note that the ```/authorsHist/``` endpoint can only return information about authors about which we have historical data (~82%).
